"""initial_schema_with_location_enum

Revision ID: 110bee039ac2
Revises: 
Create Date: 2026-05-23 17:11:07.209063

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '110bee039ac2'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('nim', sa.String(), nullable=True),
    sa.Column('nama', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.Column('role', sa.Enum('mahasiswa', 'admin', name='userrole'), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('poin', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_nim'), 'users', ['nim'], unique=True)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('tipe', sa.Enum('lost', 'found', name='itemtype'), nullable=False),
    sa.Column('status', sa.Enum('open', 'pending', 'closed', 'expired', name='itemstatus'), nullable=True),
    sa.Column('kategori', sa.Enum('elektronik', 'dompet', 'kunci', 'kartu', 'pakaian', 'tas', 'botol', 'lainnya', name='itemcategory'), nullable=False),
    sa.Column('nama_publik', sa.String(), nullable=False),
    sa.Column('deskripsi_detail', sa.Text(), nullable=True),
    sa.Column('lokasi_ditemukan', sa.String(), nullable=True),
    sa.Column('lokasi_sekarang', sa.Enum('POS_SATPAM_FAPERTA', 'POS_SATPAM_SKHB', 'POS_SATPAM_FPIK', 'POS_SATPAM_FAPET', 'POS_SATPAM_FAHUTAN', 'POS_SATPAM_FATETA', 'POS_SATPAM_FMIPA', 'POS_SATPAM_FEM', 'POS_SATPAM_FEMA', 'CCR_INFO_DESK', 'PERPUS_PUSAT_CIRCULATION', 'GKB_LOBBY', 'MASJID_AL_HURRIYYAH', 'GWW_SECURITY', 'GYMNASIUM_OFFICE', 'KLINIK_IPB', 'REKTORAT_AHN', 'STUDENT_CENTER_BEM', 'ASRAMA_PKU_PUTRA', 'ASRAMA_PKU_PUTRI', 'ASRAMA_SYLVAPINUS', 'SHELTER_BUS_REKTORAT', name='ipblocation'), nullable=True),
    sa.Column('lokasi_ditemukan_list', sa.Enum('CCR', 'GKB', 'PERPUSTAKAAN', 'MASJID_AL_HURRIYYAH', 'GYMNASIUM', 'AUDITORIUM_AHMAD_ANDI', 'ASRAMA_PUTRA', 'ASRAMA_PUTRI', 'STEVIA', 'UNGU', 'BLUE_CORNER', 'YELLOW_CORNER', 'NAYS', 'RIMBAWAN', 'SAPTA', 'PLASMA', 'KANPAT', 'IBU_SAYANG', 'MAKJAN', 'FAPERTA', 'FKH', 'FPIK', 'FAPET', 'FAHUTAN', 'FATETA', 'FMIPA', 'FEM', 'FEMA', 'SKHB', 'SB', 'SV', 'HALTE_BUS', 'JALANAN_KAMPUS', 'LAINNYA', name='itemlocation'), nullable=True),
    sa.Column('lokasi_kemungkinan_list', sa.ARRAY(sa.Enum('CCR', 'GKB', 'PERPUSTAKAAN', 'MASJID_AL_HURRIYYAH', 'GYMNASIUM', 'AUDITORIUM_AHMAD_ANDI', 'ASRAMA_PUTRA', 'ASRAMA_PUTRI', 'STEVIA', 'UNGU', 'BLUE_CORNER', 'YELLOW_CORNER', 'NAYS', 'RIMBAWAN', 'SAPTA', 'PLASMA', 'KANPAT', 'IBU_SAYANG', 'MAKJAN', 'FAPERTA', 'FKH', 'FPIK', 'FAPET', 'FAHUTAN', 'FATETA', 'FMIPA', 'FEM', 'FEMA', 'SKHB', 'SB', 'SV', 'HALTE_BUS', 'JALANAN_KAMPUS', 'LAINNYA', name='itemlocation')), nullable=True),
    sa.Column('lokasi_kemungkinan', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('bukti_kepemilikan', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('tanggal', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expired_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_items_id'), 'items', ['id'], unique=False)
    op.create_table('notifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('judul', sa.String(), nullable=False),
    sa.Column('pesan', sa.Text(), nullable=False),
    sa.Column('is_read', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notifications_id'), 'notifications', ['id'], unique=False)
    op.create_table('point_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('jumlah', sa.Integer(), nullable=False),
    sa.Column('alasan', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_point_logs_id'), 'point_logs', ['id'], unique=False)
    op.create_table('claims',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('pending', 'approved', 'rejected', name='claimstatus'), nullable=True),
    sa.Column('deskripsi_ciri', sa.Text(), nullable=False),
    sa.Column('bukti_foto', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('catatan_admin', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('kode_pengambilan', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['item_id'], ['items.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_claims_id'), 'claims', ['id'], unique=False)
    op.create_table('found_reports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lost_item_id', sa.Integer(), nullable=False),
    sa.Column('reporter_id', sa.Integer(), nullable=False),
    sa.Column('deskripsi', sa.Text(), nullable=False),
    sa.Column('lokasi_sekarang', sa.String(), nullable=False),
    sa.Column('foto_bukti', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('status', sa.Enum('pending', 'approved', 'rejected', name='foundreportstatus'), nullable=True),
    sa.Column('catatan_admin', sa.Text(), nullable=True),
    sa.Column('kode_pengambilan', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['lost_item_id'], ['items.id'], ),
    sa.ForeignKeyConstraint(['reporter_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_found_reports_id'), 'found_reports', ['id'], unique=False)
    op.create_table('item_foto',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('url', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['item_id'], ['items.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_item_foto_id'), 'item_foto', ['id'], unique=False)
    op.create_table('item_matches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('found_item_id', sa.Integer(), nullable=False),
    sa.Column('lost_item_id', sa.Integer(), nullable=False),
    sa.Column('alasan_match', sa.Text(), nullable=False),
    sa.Column('status', sa.Enum('pending', 'confirmed', 'rejected', name='matchstatus'), nullable=True),
    sa.Column('catatan_admin', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['found_item_id'], ['items.id'], ),
    sa.ForeignKeyConstraint(['lost_item_id'], ['items.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_item_matches_id'), 'item_matches', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_item_matches_id'), table_name='item_matches')
    op.drop_table('item_matches')
    op.drop_index(op.f('ix_item_foto_id'), table_name='item_foto')
    op.drop_table('item_foto')
    op.drop_index(op.f('ix_found_reports_id'), table_name='found_reports')
    op.drop_table('found_reports')
    op.drop_index(op.f('ix_claims_id'), table_name='claims')
    op.drop_table('claims')
    op.drop_index(op.f('ix_point_logs_id'), table_name='point_logs')
    op.drop_table('point_logs')
    op.drop_index(op.f('ix_notifications_id'), table_name='notifications')
    op.drop_table('notifications')
    op.drop_index(op.f('ix_items_id'), table_name='items')
    op.drop_table('items')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_nim'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
