"""update_found_report_location_to_enum

Revision ID: 5b258fe2f6ae
Revises: 110bee039ac2
Create Date: 2026-05-25 00:15:56.305165

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5b258fe2f6ae'
down_revision: Union[str, Sequence[str], None] = '110bee039ac2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("ALTER TABLE found_reports ALTER COLUMN lokasi_sekarang TYPE ipblocation USING lokasi_sekarang::ipblocation")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('found_reports', 'lokasi_sekarang',
               existing_type=sa.Enum('POS_SATPAM_FAPERTA', 'POS_SATPAM_SKHB', 'POS_SATPAM_FPIK', 'POS_SATPAM_FAPET', 'POS_SATPAM_FAHUTAN', 'POS_SATPAM_FATETA', 'POS_SATPAM_FMIPA', 'POS_SATPAM_FEM', 'POS_SATPAM_FEMA', 'CCR_INFO_DESK', 'PERPUS_PUSAT_CIRCULATION', 'GKB_LOBBY', 'MASJID_AL_HURRIYYAH', 'GWW_SECURITY', 'GYMNASIUM_OFFICE', 'KLINIK_IPB', 'REKTORAT_AHN', 'STUDENT_CENTER_BEM', 'ASRAMA_PKU_PUTRA', 'ASRAMA_PKU_PUTRI', 'ASRAMA_SYLVAPINUS', 'SHELTER_BUS_REKTORAT', name='ipblocation'),
               type_=sa.VARCHAR(),
               existing_nullable=False)
    # ### end Alembic commands ###
