"""add found_reports table

Revision ID: 5cf1dcb44972
Revises: 8cf4fc2426cd
Create Date: 2026-05-07 23:09:20.736910

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '5cf1dcb44972'
down_revision: Union[str, Sequence[str], None] = '8cf4fc2426cd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('found_reports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lost_item_id', sa.Integer(), nullable=False),
    sa.Column('reporter_id', sa.Integer(), nullable=False),
    sa.Column('deskripsi', sa.Text(), nullable=False),
    sa.Column('lokasi_sekarang', sa.String(), nullable=False),
    sa.Column('foto_bukti', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('status', sa.Enum('pending', 'approved', 'rejected', name='foundreportstatus'), nullable=True),
    sa.Column('catatan_admin', sa.Text(), nullable=True),
    sa.Column('kode_pengambilan', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['lost_item_id'], ['items.id'], ),
    sa.ForeignKeyConstraint(['reporter_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_found_reports_id'), 'found_reports', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_found_reports_id'), table_name='found_reports')
    op.drop_table('found_reports')
    # ### end Alembic commands ###
