"""update item fields and add item_matches

Revision ID: ff88796eb87a
Revises: dba6cc9bd936
Create Date: 2026-04-26 15:17:38.176207

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ff88796eb87a'
down_revision: Union[str, Sequence[str], None] = 'dba6cc9bd936'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('tipe', sa.Enum('lost', 'found', name='itemtype'), nullable=False),
    sa.Column('status', sa.Enum('open', 'pending', 'closed', 'expired', name='itemstatus'), nullable=True),
    sa.Column('kategori', sa.Enum('elektronik', 'dompet', 'kunci', 'kartu', 'pakaian', 'tas', 'botol', 'lainnya', name='itemcategory'), nullable=False),
    sa.Column('nama_publik', sa.String(), nullable=False),
    sa.Column('deskripsi_detail', sa.Text(), nullable=True),
    sa.Column('lokasi_ditemukan', sa.String(), nullable=True),
    sa.Column('lokasi_sekarang', sa.String(), nullable=True),
    sa.Column('lokasi_kemungkinan', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('bukti_kepemilikan', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('tanggal', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expired_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_items_id'), 'items', ['id'], unique=False)
    op.create_table('point_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('jumlah', sa.Integer(), nullable=False),
    sa.Column('alasan', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_point_logs_id'), 'point_logs', ['id'], unique=False)
    op.create_table('claims',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('pending', 'approved', 'rejected', name='claimstatus'), nullable=True),
    sa.Column('deskripsi_ciri', sa.Text(), nullable=False),
    sa.Column('bukti_foto', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('catatan_admin', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['item_id'], ['items.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_claims_id'), 'claims', ['id'], unique=False)
    op.create_table('item_foto',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('url', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['item_id'], ['items.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_item_foto_id'), 'item_foto', ['id'], unique=False)
    op.create_table('item_matches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('found_item_id', sa.Integer(), nullable=False),
    sa.Column('lost_item_id', sa.Integer(), nullable=False),
    sa.Column('alasan_match', sa.Text(), nullable=False),
    sa.Column('status', sa.Enum('pending', 'confirmed', 'rejected', name='matchstatus'), nullable=True),
    sa.Column('catatan_admin', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['found_item_id'], ['items.id'], ),
    sa.ForeignKeyConstraint(['lost_item_id'], ['items.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_item_matches_id'), 'item_matches', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_item_matches_id'), table_name='item_matches')
    op.drop_table('item_matches')
    op.drop_index(op.f('ix_item_foto_id'), table_name='item_foto')
    op.drop_table('item_foto')
    op.drop_index(op.f('ix_claims_id'), table_name='claims')
    op.drop_table('claims')
    op.drop_index(op.f('ix_point_logs_id'), table_name='point_logs')
    op.drop_table('point_logs')
    op.drop_index(op.f('ix_items_id'), table_name='items')
    op.drop_table('items')
    # ### end Alembic commands ###
